"""
train_classifier.py
-------------------
Step 2 of the pipeline:
  - Load denoised images produced by the autoencoder (from .npy files)
  - Build a CNN for digit classification (0–9)
  - Train and evaluate the model
  - Save the trained classifier as 'classifier.h5'
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.utils import to_categorical
import os

# ──────────────────────────────────────────────
# 1. LOAD DENOISED IMAGES & LABELS
# ──────────────────────────────────────────────
# These .npy files were generated by train_autoencoder.py
print("[INFO] Loading denoised images and labels from .npy files...")

if not os.path.exists("x_train_denoised.npy"):
    raise FileNotFoundError(
        "Denoised training images not found! "
        "Please run 'python train_autoencoder.py' first."
    )

x_train = np.load("x_train_denoised.npy")
x_test  = np.load("x_test_denoised.npy")
y_train = np.load("y_train.npy")
y_test  = np.load("y_test.npy")

print(f"[INFO] Training samples : {x_train.shape[0]}")
print(f"[INFO] Testing  samples : {x_test.shape[0]}")

# ──────────────────────────────────────────────
# 2. ONE-HOT ENCODE LABELS
# ──────────────────────────────────────────────
# Convert integer labels (0-9) to categorical one-hot vectors
# e.g., label 3 → [0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
num_classes = 10
y_train_cat = to_categorical(y_train, num_classes)
y_test_cat  = to_categorical(y_test,  num_classes)

# ──────────────────────────────────────────────
# 3. BUILD CNN CLASSIFIER
# ──────────────────────────────────────────────
print("[INFO] Building CNN Classifier...")

model = models.Sequential(name="digit_classifier_cnn")

# --- Block 1: First convolutional block ---
model.add(layers.Input(shape=(28, 28, 1)))
model.add(layers.Conv2D(32, (3, 3), activation="relu", padding="same", name="conv1"))
model.add(layers.MaxPooling2D((2, 2), name="pool1"))   # 28x28 → 14x14

# --- Block 2: Second convolutional block (deeper features) ---
model.add(layers.Conv2D(64, (3, 3), activation="relu", padding="same", name="conv2"))
model.add(layers.MaxPooling2D((2, 2), name="pool2"))   # 14x14 → 7x7

# --- Flatten + Fully-Connected Head ---
model.add(layers.Flatten(name="flatten"))
model.add(layers.Dense(128, activation="relu", name="fc1"))

# --- Output Layer: 10 neurons (one per digit class), softmax for probabilities ---
model.add(layers.Dense(num_classes, activation="softmax", name="output"))

model.summary()

# ──────────────────────────────────────────────
# 4. COMPILE & TRAIN
# ──────────────────────────────────────────────
model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",  # multi-class classification
    metrics=["accuracy"]
)

print("[INFO] Training CNN Classifier...")
model.fit(
    x_train, y_train_cat,
    epochs=5,
    batch_size=128,
    shuffle=True,
    validation_data=(x_test, y_test_cat),
    verbose=1
)

# ──────────────────────────────────────────────
# 5. EVALUATE ON TEST SET
# ──────────────────────────────────────────────
print("[INFO] Evaluating CNN on test set...")
test_loss, test_acc = model.evaluate(x_test, y_test_cat, verbose=0)
print(f"[RESULT] Test Accuracy : {test_acc * 100:.2f}%")
print(f"[RESULT] Test Loss     : {test_loss:.4f}")

# ──────────────────────────────────────────────
# 6. SAVE MODEL
# ──────────────────────────────────────────────
model_path = "classifier.keras"
model.save(model_path)
print(f"[INFO] Classifier model saved to '{model_path}'")
print("[DONE] CNN training complete!")
